### ISSUE TITLE
Roadmap for Vapor 4

### ISSUE THREAD

**Issue by b-straub** [vapor-community/HTMLKit#10]
According to the discussion [Replacing Leaf with DSL syntax](https://forums.swift.org/t/replacing-leaf-with-a-swift-dsl/25585/3), HTMLKit might be a good DSL replacement for Leaf.

Is there a roadmap when HTMLKit will be Vapor 4 ready? Currently I‘m evaluating Vapor4/LeafKit, but the HTMLKit approach looks even more promising to me since SwiftUI skills can be reused easily. With the Bootstrap add-on usage feels even more swifty.

**Comment by MatsMoll** [comment]
I would say that HTMLKit can be Vapor 4 ready very soon. I am using the latest 2.0.0 tag in my own Vapor 3 application, and I am very satisfied with the performance and development process so far. I am of course somewhat biased in my opinion tho 😂

But I created a new [repo](https://github.com/MatsMoll/htmlkit-vapor-provider) in order to add a Vapor 4 provider. This is hopefully all that is needed in order to make it possible to use it with Vapor 4. This has not been tested, but feel free to try it and add any pull requests if it is needed.

Besides this will we update for a higher-level API, and further on to a more performant rendering engine, but this will might come in a major release as this will require some breaking changes and the API is missing a few features.

**Comment by b-straub** [comment]
Thanks for the detailed feedback and the great effort. I will try the Vapor 4 provider a.s.a.p.. Basically I think the journey could go much further. When looking to the [SwiftWebUI](https://github.com/SwiftWebUI/SwiftWebUI) implementation I feel that the vapor integration could be extended by supporting e.g. automatic route generation and also the dynamic features could be similar to SwiftUI (state, binding, observed object, etc.) as already implemented there. 
The client side could support as well state changes similar to the SwiftWebUI JS support [WebUIJavaScript](https://github.com/SwiftWebUI/SwiftWebUI/blob/develop/Sources/SwiftWebUI/ViewHosting/SwiftWebUIJavaScript.swift).
I didn't touch web development for years (no need for it), but now I have some projects it could be handy having also the client side ready. This means I stepped in with a fresh mind and was shocked how basic things are still are. Vapor and a templated renderer looks far better to me than using all this JS frameworks that are dragging you on the dark side of software development.
Overall while Vapor/Leaf is a nice effort as well I think a boosted HTMLKit with some of the SwiftWebUI ideas would be a far better approach.

**Comment by b-straub** [comment]
I tried the Vapor 4 provider and most things are working well, however I couldn't succeed with the Alert example because of a "missingLingoConfig" error.

**Comment by MatsMoll** [comment]
Awesome to hear! 
And let me know if there are any changes you would have liked
