### ISSUE TITLE
Why template instantiation throws?

### ISSUE THREAD

**Issue by isaac-weisberg** [vapor-community/HTMLKit#12]
I've noticed that the template instantiation features using a throwing init. It even states it in the readme
```
try SimpleTemplate()
```
But why does it throw? What can go wrong during instantiation?

**Comment by MatsMoll** [comment]
This is because of the `render(...)` function (that is from the Vapor [provider](https://github.com/MatsMoll/htmlkit-vapor-provider)) as there was a possibility that the template was not registered to the cached renderer. However, this exact problem has been fixed in a new update. 

So now is it only a way of making it *safer* in case the template is compiled incorrectly for some reason. This should not happen though
