### ISSUE TITLE
Access raw value from TemplateValue

### ISSUE THREAD

**Issue by Magiguigui** [vapor-community/HTMLKit#17]
```swift
public struct ListPage<O: AnyModel, V: CustomStringConvertible>: HTMLTemplate {

	// MARK: - Context
	public struct Context {

		public var base: Template.Context

		public var objects: [O]
		public var properties: [KeyPath<O, V>]
	}

	@TemplateValue(Context.self) public var context

	// MARK: - Body
	public var body: HTML {
		Template(context: self.context.base) {
			ForEach(in: self.context.objects) { object in
				ForEach(in: self.context.properties) { property in
					P { "\(object[keyPath: property].description)" }
				}
			}
		}
	}

}
```

That's a really little example showing the issue I am encountering.
There is a way to unwrap values from TemplateValue ? 
How my objects/properties properties from Context are TemplateValue even if I didn't flag them ?

Thx

**Comment by MatsMoll** [comment]
I would recommend creating a computed property that returns an array of `V` and loop through them
```swift
extension ListPage.Context {
    var values: [[String]] { objects.map { object in properties.map { object[keyPath: $0].description } }
}
```
And then you can use it with HTMLKit like
```swift
ForEach(in: values) { strings in
    ForEach(in: strings) { string in
        P { string }
    }
}
```
Unfortunately, your approach with string interpolation and looping through the key paths in HTMLKit will not work as the values are wrapped in a `TemplateValue` type. This helps HTMLKit in order to optimize the template for faster rendering speeds, but it also limits the usage a bit.
