### ISSUE TITLE
HTMLComponent rendered as String?

### ISSUE THREAD

**Issue by Magiguigui** [vapor-community/HTMLKit#18]
Hello 
When i am trying to render a template nesting other HTML components they are rendered as String:

```swift
public struct HTMLFieldComponent: HTMLComponent {

	var content: HTML

	init(@HTMLBuilder builder: () -> HTML) {
		self.content = builder()
	}

	public var body: HTML {
		self.content
	}

}

public protocol FormFieldRepresentable {

	var html: HTMLField { get }

}

extension StringField: FormFieldRepresentable {

	...

	public var html: HTMLField {
		HTMLField {
			Label {
				self.label
			}.class("control-label").for(self.key)
			Input(type: .text, id: self.key).class("form-control")
		}
	}

}

struct CreatePage: HTMLTemplate {

	public struct Context {
		var fields: [FormFieldRepresentable]

		init(with fields: [FormFieldRepresentable]) {
			self.fields = fields
		}
	}

	@TemplateValue(Context.self)
	public var context

	public var body: HTML {
		TemplatedDocument {
			Row {
				ForEach(in: self.context.fields) { field in
					field.html
				}			
			}
		}
	}

}
```

Result: 

```html
<div class="row">
	"<label  >Email</label><input   >"
	"<label  >Email</label><input   >"
</div>
```

The components are well rendered if they are not reached from `field.html` but written statically.

**Comment by MatsMoll** [comment]
The problem here is that the attributes contain an `IF` condition this has not been pre-rendered since it is passed through the `Context`. 

The fix for this will unfortunately have a performance hit. And I would believe that it is possible to render a similar template by changing the structure a bit. So because of the performance hit of almost 20%, will I probably not push an update for this. unfortunately.
