### ISSUE TITLE
Help to use your framework

### ISSUE THREAD

**Issue by raulsilvamx** [vapor-community/HTMLKit#21]
Hello @MatsMoll:

I newbie with vapor and I try to use your framework but only have compilation errors, even Xcode doesn't let me build my app could you help us how use it please. Thank you. I sent you my errors...

```
    router.get("markdown") { req in
        return try KORVHomeTemplate().render(with: .init(title: "Home Page", author: "Raul Silva", twitter: "@raulsilvamx"))
    }

```

**'HTMLRenderer.ContextManager<Context>' initializer is inaccessible due to 'internal' protection level**

**Comment by MatsMoll** [comment]
Thanks for checking out HTMLKit @raulsilvamx! 

As the error is indicating, you are using an internal function that HTMLKit uses. So this means you won't be able to use that exact one. 

However, the fix is very simple. In order to make it work, just add `for: req` at the end. Like this:
```swift
try KORVHomeTemplate().render(
    with: .init(title: "Home Page", author: "Raul Silva", twitter: "@raulsilvamx"), 
    for: req
)

```

**Comment by renaudjenny** [comment]
Hi @MatsMoll,
Before all, thanks for the great work here!

Unfortunately, I'm not able to use it in my project for some obscures reasons 😞.

My code in Controller looks like this:

```swift
    func get(req: Request) throws -> EventLoopFuture<String> {
        guard
        let groomingSessionIdString = req.parameters.get("groomingSessionID"),
        let groomingSessionId = UUID(uuidString: groomingSessionIdString)
        else {
            return req.eventLoop.makeFailedFuture(Abort(.badRequest))
        }

        return GroomingSession.query(on: req.db)
            .filter(\.$id == groomingSessionId)
            .with(\.$userStories)
            .first()
            .unwrap(or: Abort(.notFound))
            .flatMapThrowing {
                try GroomingSessionTemplate().render(
                    with: .init(groomingSession: $0),
                    for: req
                )
            }
    }
```
Xcode throw me an error for the exact same reason as @raulsilvamx, `HTMLRenderer.ContextManager<Context>' initializer is inaccessible due to 'internal' protection level ` + `Extra argument 'for' in call`

In the README the example says: `try SimpleTemplate().render(with: .init(...), for: req)` However, it's not easy to guess what's inside the `.init(...)`, might it be that?

Don't hesitate to indicate me the response and I can do a PR to improve the doc if you think it deserves it ☺️.

Thanks.
