### ISSUE TITLE
Does it support parse html node

### ISSUE THREAD

**Issue by knight2010** [vapor-community/HTMLKit#55]
If I could use it like, SwiftSoup, It can not use in the vapor project. 
I am searching one like SwiftSoup, which can crawl some elements of html.

**Comment by mattesmohr** [comment]
Hey @knight2010, what do you mean with crawl? Can you explain it a bit more?

**Comment by knight2010** [comment]
> Hey @knight2010, what do you mean with crawl? Can you explain it a bit more?
> 
> HTMLKit is not a parser particularly. Its a DSL to create HTML templates by using Swift.

Oh sorry, I am looking some lib to parse html element. Is there any way or library to use.

**Comment by mattesmohr** [comment]
Especially in use with Vapor unfortunately I don't know. I don't see any parser in the vapor community. You can ask the vapor community on the discord server. Maybe some of the developers have experience with it. But since SwiftSoup is a swift package, it should be useable with Vapor. But don't take my words for granted.

If it answers your question and there is no further HTMLKit related question. I would appreciate it if you close the issue.
